//
//  Copyright (c) Microsoft Corporation. All rights reserved.
//  Licensed under the MIT License.
//

import AppKit
import FluentUI

class TestLinkViewController: NSViewController {
	override func loadView() {
		let linkWithNoHover = Link(title: "Link to Bing", url: NSURL(string: "https://wwww.bing.com")!)
		
		let linkWithHover = Link(title: "Link to Bing with hover effects", url: NSURL(string: "https://wwww.bing.com")!)
		linkWithHover.showsUnderlineWhileMouseInside = true
		
		let linkWithHoverAndNoURL = Link(title: "Link with hover effects and no URL")
		linkWithHoverAndNoURL.showsUnderlineWhileMouseInside = true
		
		let linkWithOverridenTargetAction = Link(frame: .zero)
		linkWithOverridenTargetAction.title = "Link with overridden Target/Action"
		linkWithOverridenTargetAction.showsUnderlineWhileMouseInside = true
		linkWithOverridenTargetAction.target = self
		linkWithOverridenTargetAction.action = #selector(displayAlert)
		
		let containerView = NSStackView(views: [linkWithNoHover, linkWithHover, linkWithHoverAndNoURL, linkWithOverridenTargetAction])
		containerView.edgeInsets = NSEdgeInsets(top: 100, left: 100, bottom: 100, right: 100)
		containerView.orientation = .vertical
		containerView.distribution = .gravityAreas
		view = containerView
	}
	
	@objc private func displayAlert() {
		let alert = NSAlert()
        alert.messageText = "Alert"
        alert.informativeText = "This is an alert generated by a Link with an overridden Target/Action"
		alert.runModal()
	}
}
