// swiftlint:disable all
/// Autogenerated file
import UIKit

/// Entry point for the app stylesheet
extension FluentUIStyle {

	// MARK: - MSFPillButtonBarTokens
	open var MSFPillButtonBarTokens: MSFPillButtonBarTokensAppearanceProxy {
		return MSFPillButtonBarTokensAppearanceProxy(proxy: { return self })
	}
	open class MSFPillButtonBarTokensAppearanceProxy {
		public let mainProxy: () -> FluentUIStyle
		public init(proxy: @escaping () -> FluentUIStyle) {
			self.mainProxy = proxy
		}

		// MARK: - cornerRadius 
		open var cornerRadius: CGFloat {
			return CGFloat(16.0)
		}

		// MARK: - maxButtonsSpacing 
		open var maxButtonsSpacing: CGFloat {
			return CGFloat(10.0)
		}

		// MARK: - minButtonVisibleWidth 
		open var minButtonVisibleWidth: CGFloat {
			return CGFloat(20.0)
		}

		// MARK: - minButtonWidth 
		open var minButtonWidth: CGFloat {
			return CGFloat(56.0)
		}

		// MARK: - minButtonsSpacing 
		open var minButtonsSpacing: CGFloat {
			return CGFloat(8.0)
		}

		// MARK: - minHeight 
		open var minHeight: CGFloat {
			return CGFloat(28.0)
		}

		// MARK: - sideInset 
		open var sideInset: CGFloat {
			return CGFloat(16.0)
		}
	}

}
fileprivate var __AppearanceProxyHandle: UInt8 = 0
fileprivate var __ThemeAwareHandle: UInt8 = 0
fileprivate var __ObservingDidChangeThemeHandle: UInt8 = 0

extension MSFPillButtonBarTokens: AppearaceProxyComponent {

	public typealias AppearanceProxyType = FluentUIStyle.MSFPillButtonBarTokensAppearanceProxy
	public var appearanceProxy: AppearanceProxyType {
		get {
			if let proxy = objc_getAssociatedObject(self, &__AppearanceProxyHandle) as? AppearanceProxyType {
				if !themeAware { return proxy }


				return proxy
			}

			return FluentUIThemeManager.stylesheet(FluentUIStyle.shared()).MSFPillButtonBarTokens
		}
		set {
			objc_setAssociatedObject(self, &__AppearanceProxyHandle, newValue, .OBJC_ASSOCIATION_RETAIN_NONATOMIC)
			didChangeAppearanceProxy()
		}
	}

	public var themeAware: Bool {
		get {
			guard let proxy = objc_getAssociatedObject(self, &__ThemeAwareHandle) as? Bool else { return true }
			return proxy
		}
		set {
			objc_setAssociatedObject(self, &__ThemeAwareHandle, newValue, .OBJC_ASSOCIATION_RETAIN_NONATOMIC)
			isObservingDidChangeTheme = newValue
		}
	}

	fileprivate var isObservingDidChangeTheme: Bool {
		get {
			guard let observing = objc_getAssociatedObject(self, &__ObservingDidChangeThemeHandle) as? Bool else { return false }
			return observing
		}
		set {
			if newValue == isObservingDidChangeTheme { return }
			if newValue {
				NotificationCenter.default.addObserver(self, selector: #selector(didChangeAppearanceProxy), name: Notification.Name.didChangeTheme, object: nil)
			} else {
				NotificationCenter.default.removeObserver(self, name: Notification.Name.didChangeTheme, object: nil)
			}
			objc_setAssociatedObject(self, &__ObservingDidChangeThemeHandle, newValue, .OBJC_ASSOCIATION_RETAIN_NONATOMIC)
		}
	}
}
