/// Autogenerated file

// swiftlint:disable all
import UIKit

public class Application {
	@objc dynamic public class func preferredContentSizeCategory() -> UIContentSizeCategory {
		return .large
	}
}

fileprivate var __ApperanceProxyHandle: UInt8 = 0
fileprivate var __ThemeAwareHandle: UInt8 = 0
fileprivate var __ObservingDidChangeThemeHandle: UInt8 = 0

/// Your view should conform to 'AppearaceProxyComponent'.
public protocol AppearaceProxyComponent: class {
	associatedtype ApperanceProxyType
	var appearanceProxy: ApperanceProxyType { get }
	var themeAware: Bool { get set }
	func didChangeAppearanceProxy()
}

public extension AppearaceProxyComponent {
	func initAppearanceProxy(themeAware: Bool = true) {
		self.themeAware = themeAware
		didChangeAppearanceProxy()
	}
}

#if os(iOS)
private let defaultSizes: [UIFont.TextStyle: CGFloat] = {
	var sizes: [UIFont.TextStyle: CGFloat] = [.caption2: 11,
	.caption1: 12,
	.footnote: 13,
	.subheadline: 15,
	.callout: 16,
	.body: 17,
	.headline: 17,
	.title3: 20,
	.title2: 22,
	.title1: 28]
	if #available(iOS 11.0, *) {
		sizes[.largeTitle] = 34
	}
	return sizes
}()
#elseif os(tvOS)
private let defaultSizes: [UIFont.TextStyle: CGFloat] =
	[.caption2: 23,
		.caption1: 25,
		.footnote: 29,
		.subheadline: 29,
		.body: 29,
		.callout: 31,
		.headline: 38,
		.title3: 48,
		.title2: 57,
		.title1: 76]
#elseif os(watchOS)
private let defaultSizes: [UIFont.TextStyle: CGFloat] = {
	if #available(watchOS 5.0, *) {
		switch WKInterfaceDevice.current().preferredContentSizeCategory {
		case "UICTContentSizeCategoryS":
			return [.footnote: 12,
				.caption2: 13,
				.caption1: 14,
				.body: 15,
				.headline: 15,
				.title3: 18,
				.title2: 26,
				.title1: 30,
				.largeTitle: 32]
		case "UICTContentSizeCategoryL":
			return [.footnote: 13,
				.caption2: 14,
				.caption1: 15,
				.body: 16,
				.headline: 16,
				.title3: 19,
				.title2: 27,
				.title1: 34,
				.largeTitle: 36]
		case "UICTContentSizeCategoryXL":
			return [.footnote: 14,
				.caption2: 15,
				.caption1: 16,
				.body: 17,
				.headline: 17,
				.title3: 20,
				.title2: 30,
				.title1: 38,
				.largeTitle: 40]
		default:
			return [:]
		}
	} else {
		/// No `largeTitle` before watchOS 5
		switch WKInterfaceDevice.current().preferredContentSizeCategory {
		case "UICTContentSizeCategoryS":
			return [.footnote: 12,
					.caption2: 13,
					.caption1: 14,
					.body: 15,
					.headline: 15,
					.title3: 18,
					.title2: 26,
					.title1: 30]
		case "UICTContentSizeCategoryL":
			return [.footnote: 13,
					.caption2: 14,
					.caption1: 15,
					.body: 16,
					.headline: 16,
					.title3: 19,
					.title2: 27,
					.title1: 34]
		default:
			return [:]
		}
	}
}()
#endif

public extension S.IconicFontStyle {
	var name: String {
		switch self {
			case .light: return StylesheetManager.S.__SymbolFont.lightFontName
			case .regular: return StylesheetManager.S.__SymbolFont.regularFontName
		}
	}
}

fileprivate var __ScalableHandle: UInt8 = 0
public extension UIFont {
	convenience init?(style: S.IconicFontStyle, size: CGFloat) {
		self.init(name: style.name, size: size)
	}

	static func scaledFont(name: String, textStyle: UIFont.TextStyle, traitCollection: UITraitCollection? = nil) -> UIFont {
		if #available(iOS 11.0, *) {
			guard let defaultSize = defaultSizes[textStyle], let customFont = UIFont(name: name, size: defaultSize) else {
				fatalError("Failed to load the \(name) font.")
			}
			return UIFontMetrics(forTextStyle: textStyle).scaledFont(for: customFont, compatibleWith: traitCollection)
		} else {
			let fontDescriptor = UIFontDescriptor.preferredFontDescriptor(withTextStyle: textStyle, compatibleWith: traitCollection)
			guard let customFont = UIFont(name: name, size: fontDescriptor.pointSize) else {
				fatalError("Failed to load the \(name) font.")
			}
			return customFont
		}
	}

	func with(traits: UIFontDescriptor.SymbolicTraits) -> UIFont {
		let descriptor = fontDescriptor.withSymbolicTraits(traits)
		return UIFont(descriptor: descriptor!, size: 0)
	}

	class func preferredFont(forTextStyle style: UIFont.TextStyle, compatibleWith traitCollection: UITraitCollection?, scalable: Bool) -> UIFont {
		let font = UIFont.preferredFont(forTextStyle: style, compatibleWith: traitCollection)
		font.isScalable = true
		return font
	}

	convenience init?(name: String, scalable: Bool) {
		self.init(name: name, size: 4)
		self.isScalable = scalable
	}

	var isScalable: Bool {
		get { return objc_getAssociatedObject(self, &__ScalableHandle) as? Bool ?? false }
		set { objc_setAssociatedObject(self, &__ScalableHandle, newValue, .OBJC_ASSOCIATION_RETAIN_NONATOMIC) }
	}

}

public extension Notification.Name {
	static let didChangeTheme = Notification.Name("stardust.stylesheet.theme")
}

protocol StylesheetManagerTheming {
	static func currentTheme() -> GenericStyle
	func themeInit()
}

extension StylesheetManagerTheming {
	static func currentTheme() -> GenericStyle {
		return GenericStyle.shared()
	}
	func themeInit() {
		
	}
}

@objcMembers public class StylesheetManager: NSObject, StylesheetManagerTheming {
	dynamic public class func stylesheet(_ stylesheet: GenericStyle) -> GenericStyle {
		return currentTheme()
	}

	public static let `default` = StylesheetManager()
	public static var S: GenericStyle {
		return currentTheme()
	}

	private override init() {
		super.init()
		themeInit()
	}
}

public struct S {

public enum IconicFontStyle {
	case light
	case regular
}

}
/// Entry point for the app stylesheet
@objc(STRGenericStyle) @objcMembers public class GenericStyle: NSObject {

	public class func shared() -> GenericStyle {
		 struct __ { static let _sharedInstance = GenericStyle() }
		return __._sharedInstance
	}
	//MARK: - Button
	public var _Button: ButtonAppearanceProxy?
	open func ButtonStyle() -> ButtonAppearanceProxy {
		if let override = _Button { return override }
			return ButtonAppearanceProxy(proxy: { return GenericStyle.shared() })
		}
	public var Button: ButtonAppearanceProxy {
		get { return self.ButtonStyle() }
		set { _Button = newValue }
	}
	@objc(ButtonAppearanceProxy) @objcMembers open class ButtonAppearanceProxy: NSObject {
		public let mainProxy: () -> GenericStyle
		public init(proxy: @escaping () -> GenericStyle) {
			self.mainProxy = proxy
		}

		//MARK: - borderWidth
		public var _borderWidth: borderWidthAppearanceProxy?
		open func borderWidthStyle() -> borderWidthAppearanceProxy {
			if let override = _borderWidth { return override }
				return borderWidthAppearanceProxy(proxy: mainProxy)
			}
		public var borderWidth: borderWidthAppearanceProxy {
			get { return self.borderWidthStyle() }
			set { _borderWidth = newValue }
		}
		@objc(ButtonBorderWidthAppearanceProxy) @objcMembers open class borderWidthAppearanceProxy: NSObject {
			public let mainProxy: () -> GenericStyle
			public init(proxy: @escaping () -> GenericStyle) {
				self.mainProxy = proxy
			}

			//MARK: normal 
			public var _normal: CGFloat?
			open func normalProperty(_ traitCollection: UITraitCollection? = UIScreen.main.traitCollection) -> CGFloat {
				if let override = _normal { return override }
					return CGFloat(1.0)
				}
			public var normal: CGFloat {
				get { return self.normalProperty() }
				set { _normal = newValue }
			}
		}

	}
	//MARK: - TextButton
	public var _TextButton: TextButtonAppearanceProxy?
	open func TextButtonStyle() -> TextButtonAppearanceProxy {
		if let override = _TextButton { return override }
			return TextButtonAppearanceProxy(proxy: { return GenericStyle.shared() })
		}
	public var TextButton: TextButtonAppearanceProxy {
		get { return self.TextButtonStyle() }
		set { _TextButton = newValue }
	}
	@objc(TextButtonAppearanceProxy) @objcMembers open class TextButtonAppearanceProxy: ButtonAppearanceProxy {

		//MARK: - TextButtonborderWidth
		override open func borderWidthStyle() -> ButtonAppearanceProxy.borderWidthAppearanceProxy {
			if let override = _borderWidth { return override }
				return TextButtonborderWidthAppearanceProxy(proxy: mainProxy)
			}
		@objc(TextButtonBorderWidthAppearanceProxy) @objcMembers open class TextButtonborderWidthAppearanceProxy: ButtonAppearanceProxy.borderWidthAppearanceProxy {

			//MARK: normal 
			override open func normalProperty(_ traitCollection: UITraitCollection? = UIScreen.main.traitCollection) -> CGFloat {
				if let override = _normal { return override }
					return CGFloat(0.0)
				}
		}


		//MARK: - color
		public var _color: colorAppearanceProxy?
		open func colorStyle() -> colorAppearanceProxy {
			if let override = _color { return override }
				return colorAppearanceProxy(proxy: mainProxy)
			}
		public var color: colorAppearanceProxy {
			get { return self.colorStyle() }
			set { _color = newValue }
		}
		@objc(TextButtonColorAppearanceProxy) @objcMembers open class colorAppearanceProxy: NSObject {
			public let mainProxy: () -> GenericStyle
			public init(proxy: @escaping () -> GenericStyle) {
				self.mainProxy = proxy
			}

			//MARK: normal 
			public var _normal: CGFloat?
			open func normalProperty(_ traitCollection: UITraitCollection? = UIScreen.main.traitCollection) -> CGFloat {
				if let override = _normal { return override }
					return CGFloat(10.0)
				}
			public var normal: CGFloat {
				get { return self.normalProperty() }
				set { _normal = newValue }
			}
		}

	}
	//MARK: - Theme
	public var _Theme: ThemeAppearanceProxy?
	open func ThemeStyle() -> ThemeAppearanceProxy {
		if let override = _Theme { return override }
			return ThemeAppearanceProxy(proxy: { return GenericStyle.shared() })
		}
	public var Theme: ThemeAppearanceProxy {
		get { return self.ThemeStyle() }
		set { _Theme = newValue }
	}
	@objc(ThemeAppearanceProxy) @objcMembers open class ThemeAppearanceProxy: NSObject {
		public let mainProxy: () -> GenericStyle
		public init(proxy: @escaping () -> GenericStyle) {
			self.mainProxy = proxy
		}

		//MARK: generic 
		public var _generic: Bool?
		open func genericProperty(_ traitCollection: UITraitCollection? = UIScreen.main.traitCollection) -> Bool {
			if let override = _generic { return override }
			return true
			}
		public var generic: Bool {
			get { return self.genericProperty() }
			set { _generic = newValue }
		}
	}
	//MARK: - __SymbolFont
	public var ___SymbolFont: __SymbolFontAppearanceProxy?
	open func __SymbolFontStyle() -> __SymbolFontAppearanceProxy {
		if let override = ___SymbolFont { return override }
			return __SymbolFontAppearanceProxy(proxy: { return GenericStyle.shared() })
		}
	public var __SymbolFont: __SymbolFontAppearanceProxy {
		get { return self.__SymbolFontStyle() }
		set { ___SymbolFont = newValue }
	}
	@objc(__SymbolFontAppearanceProxy) @objcMembers open class __SymbolFontAppearanceProxy: NSObject {
		public let mainProxy: () -> GenericStyle
		public init(proxy: @escaping () -> GenericStyle) {
			self.mainProxy = proxy
		}

		//MARK: lightFontName 
		public var _lightFontName: String?
		open func lightFontNameProperty(_ traitCollection: UITraitCollection? = UIScreen.main.traitCollection) -> String {
			if let override = _lightFontName { return override }
			return "StardustAssetsUNI-Light"
			}
		public var lightFontName: String {
			get { return self.lightFontNameProperty() }
			set { _lightFontName = newValue }
		}

		//MARK: regularFontName 
		public var _regularFontName: String?
		open func regularFontNameProperty(_ traitCollection: UITraitCollection? = UIScreen.main.traitCollection) -> String {
			if let override = _regularFontName { return override }
			return "StardustAssetsUNI-Light"
			}
		public var regularFontName: String {
			get { return self.regularFontNameProperty() }
			set { _regularFontName = newValue }
		}
	}

}
extension Button: AppearaceProxyComponent {

	public typealias ApperanceProxyType = GenericStyle.ButtonAppearanceProxy
	public var appearanceProxy: ApperanceProxyType {
		get {
			if let proxy = objc_getAssociatedObject(self, &__ApperanceProxyHandle) as? ApperanceProxyType {
				if !themeAware { return proxy }

				if proxy is GenericStyle.TextButtonAppearanceProxy {
					return StylesheetManager.stylesheet(GenericStyle.shared()).TextButton
				}
				return proxy
			}

			return StylesheetManager.stylesheet(GenericStyle.shared()).Button
		}
		set {
			objc_setAssociatedObject(self, &__ApperanceProxyHandle, newValue, .OBJC_ASSOCIATION_RETAIN_NONATOMIC)
			didChangeAppearanceProxy()
		}
	}

	public var themeAware: Bool {
		get {
			guard let proxy = objc_getAssociatedObject(self, &__ThemeAwareHandle) as? Bool else { return true }
			return proxy
		}
		set {
			objc_setAssociatedObject(self, &__ThemeAwareHandle, newValue, .OBJC_ASSOCIATION_RETAIN_NONATOMIC)
			isObservingDidChangeTheme = newValue
		}
	}

	fileprivate var isObservingDidChangeTheme: Bool {
		get {
			guard let observing = objc_getAssociatedObject(self, &__ObservingDidChangeThemeHandle) as? Bool else { return false }
			return observing
		}
		set {
			if newValue == isObservingDidChangeTheme { return }
			if newValue {
				NotificationCenter.default.addObserver(self, selector: #selector(didChangeAppearanceProxy), name: Notification.Name.didChangeTheme, object: nil)
			} else {
				NotificationCenter.default.removeObserver(self, name: Notification.Name.didChangeTheme, object: nil)
			}
			objc_setAssociatedObject(self, &__ObservingDidChangeThemeHandle, newValue, .OBJC_ASSOCIATION_RETAIN_NONATOMIC)
		}
	}
}
