// swiftlint:disable all
/// Autogenerated file
import UIKit

/// Entry point for the app stylesheet
extension FluentUIStyle {

	//MARK: - MSFAccentAvatarTokens
	open var MSFAccentAvatarTokens: MSFAccentAvatarTokensAppearanceProxy {
		return MSFAccentAvatarTokensAppearanceProxy(proxy: { return self })
	}
	open class MSFAccentAvatarTokensAppearanceProxy: MSFAvatarTokensAppearanceProxy {

		//MARK: backgroundDefaultColor 
		open override var backgroundDefaultColor: UIColor { 
			return mainProxy().Colors.Brand.primary 
		}

		//MARK: foregroundDefaultColor 
		open override var foregroundDefaultColor: UIColor { 
			return mainProxy().Icon.accentColor 
		}

		//MARK: ringDefaultColor 
		open override var ringDefaultColor: UIColor { 
			return mainProxy().Colors.Brand.shade10 
		}
	}
	//MARK: - MSFAvatarTokens
	open var MSFAvatarTokens: MSFAvatarTokensAppearanceProxy {
		return MSFAvatarTokensAppearanceProxy(proxy: { return self })
	}
	open class MSFAvatarTokensAppearanceProxy {
		public let mainProxy: () -> FluentUIStyle
		public init(proxy: @escaping () -> FluentUIStyle) {
			self.mainProxy = proxy
		}

		//MARK: backgroundDefaultColor 
		open var backgroundDefaultColor: UIColor { 
			return UIColor(light: mainProxy().Colors.Neutral.white, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Brand.primary, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil) 
		}

		//MARK: - borderRadius
		open var borderRadius: borderRadiusAppearanceProxy {
			return borderRadiusAppearanceProxy(proxy: mainProxy)
		}
		open class borderRadiusAppearanceProxy {
			public let mainProxy: () -> FluentUIStyle
			public init(proxy: @escaping () -> FluentUIStyle) {
				self.mainProxy = proxy
			}

			//MARK: large 
			open var large: CGFloat { 
					return mainProxy().Border.radius.none 
			}

			//MARK: medium 
			open var medium: CGFloat { 
					return mainProxy().Border.radius.none 
			}

			//MARK: small 
			open var small: CGFloat { 
					return mainProxy().Border.radius.none 
			}

			//MARK: xSmall 
			open var xSmall: CGFloat { 
					return mainProxy().Border.radius.none 
			}

			//MARK: xlarge 
			open var xlarge: CGFloat { 
					return mainProxy().Border.radius.none 
			}

			//MARK: xxlarge 
			open var xxlarge: CGFloat { 
					return mainProxy().Border.radius.none 
			}
		}


		//MARK: foregroundDefaultColor 
		open var foregroundDefaultColor: UIColor { 
			return UIColor(light: mainProxy().Colors.Brand.primary, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Icon.accentColor, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil) 
		}

		//MARK: presenceIconOutlineColor 
		open var presenceIconOutlineColor: UIColor { 
			return mainProxy().Colors.Background.neutral1 
		}

		//MARK: - presenceIconOutlineThickness
		open var presenceIconOutlineThickness: presenceIconOutlineThicknessAppearanceProxy {
			return presenceIconOutlineThicknessAppearanceProxy(proxy: mainProxy)
		}
		open class presenceIconOutlineThicknessAppearanceProxy {
			public let mainProxy: () -> FluentUIStyle
			public init(proxy: @escaping () -> FluentUIStyle) {
				self.mainProxy = proxy
			}

			//MARK: large 
			open var large: CGFloat { 
					return mainProxy().Border.size.thick 
			}

			//MARK: medium 
			open var medium: CGFloat { 
					return mainProxy().Border.size.thick 
			}

			//MARK: small 
			open var small: CGFloat { 
					return mainProxy().Border.size.thick 
			}

			//MARK: xSmall 
			open var xSmall: CGFloat { 
					return mainProxy().Border.size.none 
			}

			//MARK: xlarge 
			open var xlarge: CGFloat { 
					return mainProxy().Border.size.thick 
			}

			//MARK: xxlarge 
			open var xxlarge: CGFloat { 
					return mainProxy().Border.size.thick 
			}
		}


		//MARK: - presenceIconSize
		open var presenceIconSize: presenceIconSizeAppearanceProxy {
			return presenceIconSizeAppearanceProxy(proxy: mainProxy)
		}
		open class presenceIconSizeAppearanceProxy {
			public let mainProxy: () -> FluentUIStyle
			public init(proxy: @escaping () -> FluentUIStyle) {
				self.mainProxy = proxy
			}

			//MARK: large 
			open var large: CGFloat { 
					return mainProxy().Icon.size.xxSmall 
			}

			//MARK: medium 
			open var medium: CGFloat { 
					return mainProxy().Icon.size.xxxSmall 
			}

			//MARK: small 
			open var small: CGFloat { 
					return mainProxy().Icon.size.xxxSmall 
			}

			//MARK: xSmall 
			open var xSmall: CGFloat { 
					return CGFloat(0.0) 
			}

			//MARK: xlarge 
			open var xlarge: CGFloat { 
					return mainProxy().Icon.size.xxSmall 
			}

			//MARK: xxlarge 
			open var xxlarge: CGFloat { 
					return mainProxy().Icon.size.small 
			}
		}


		//MARK: ringDefaultColor 
		open var ringDefaultColor: UIColor { 
			return mainProxy().Colors.Brand.tint10 
		}

		//MARK: ringGapColor 
		open var ringGapColor: UIColor { 
			return mainProxy().Colors.Background.neutral1 
		}

		//MARK: - ringInnerGap
		open var ringInnerGap: ringInnerGapAppearanceProxy {
			return ringInnerGapAppearanceProxy(proxy: mainProxy)
		}
		open class ringInnerGapAppearanceProxy {
			public let mainProxy: () -> FluentUIStyle
			public init(proxy: @escaping () -> FluentUIStyle) {
				self.mainProxy = proxy
			}

			//MARK: large 
			open var large: CGFloat { 
					return mainProxy().Border.size.thick 
			}

			//MARK: medium 
			open var medium: CGFloat { 
					return mainProxy().Border.size.thick 
			}

			//MARK: small 
			open var small: CGFloat { 
					return mainProxy().Border.size.thick 
			}

			//MARK: xSmall 
			open var xSmall: CGFloat { 
					return mainProxy().Border.size.thick 
			}

			//MARK: xlarge 
			open var xlarge: CGFloat { 
					return mainProxy().Border.size.thick 
			}

			//MARK: xxlarge 
			open var xxlarge: CGFloat { 
					return mainProxy().Border.size.thicker 
			}
		}


		//MARK: - ringOuterGap
		open var ringOuterGap: ringOuterGapAppearanceProxy {
			return ringOuterGapAppearanceProxy(proxy: mainProxy)
		}
		open class ringOuterGapAppearanceProxy {
			public let mainProxy: () -> FluentUIStyle
			public init(proxy: @escaping () -> FluentUIStyle) {
				self.mainProxy = proxy
			}

			//MARK: large 
			open var large: CGFloat { 
					return mainProxy().Border.size.thick 
			}

			//MARK: medium 
			open var medium: CGFloat { 
					return mainProxy().Border.size.thick 
			}

			//MARK: small 
			open var small: CGFloat { 
					return mainProxy().Border.size.thick 
			}

			//MARK: xSmall 
			open var xSmall: CGFloat { 
					return mainProxy().Border.size.thick 
			}

			//MARK: xlarge 
			open var xlarge: CGFloat { 
					return mainProxy().Border.size.thick 
			}

			//MARK: xxlarge 
			open var xxlarge: CGFloat { 
					return mainProxy().Border.size.thicker 
			}
		}


		//MARK: - ringThickness
		open var ringThickness: ringThicknessAppearanceProxy {
			return ringThicknessAppearanceProxy(proxy: mainProxy)
		}
		open class ringThicknessAppearanceProxy {
			public let mainProxy: () -> FluentUIStyle
			public init(proxy: @escaping () -> FluentUIStyle) {
				self.mainProxy = proxy
			}

			//MARK: large 
			open var large: CGFloat { 
					return mainProxy().Border.size.thick 
			}

			//MARK: medium 
			open var medium: CGFloat { 
					return mainProxy().Border.size.thick 
			}

			//MARK: small 
			open var small: CGFloat { 
					return mainProxy().Border.size.thin 
			}

			//MARK: xSmall 
			open var xSmall: CGFloat { 
					return mainProxy().Border.size.thin 
			}

			//MARK: xlarge 
			open var xlarge: CGFloat { 
					return mainProxy().Border.size.thick 
			}

			//MARK: xxlarge 
			open var xxlarge: CGFloat { 
					return mainProxy().Border.size.thicker 
			}
		}


		//MARK: - size
		open var size: sizeAppearanceProxy {
			return sizeAppearanceProxy(proxy: mainProxy)
		}
		open class sizeAppearanceProxy {
			public let mainProxy: () -> FluentUIStyle
			public init(proxy: @escaping () -> FluentUIStyle) {
				self.mainProxy = proxy
			}

			//MARK: large 
			open var large: CGFloat { 
					return CGFloat(40.0) 
			}

			//MARK: medium 
			open var medium: CGFloat { 
					return CGFloat(32.0) 
			}

			//MARK: small 
			open var small: CGFloat { 
					return CGFloat(24.0) 
			}

			//MARK: xSmall 
			open var xSmall: CGFloat { 
					return CGFloat(16.0) 
			}

			//MARK: xlarge 
			open var xlarge: CGFloat { 
					return CGFloat(52.0) 
			}

			//MARK: xxlarge 
			open var xxlarge: CGFloat { 
					return CGFloat(72.0) 
			}
		}


		//MARK: textCalculatedBackgroundColors 
		open var textCalculatedBackgroundColors: [UIColor] { 
			return [
			UIColor(light: mainProxy().Colors.DarkRed.tint40, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.DarkRed.shade30, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.Cranberry.tint40, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Cranberry.shade30, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.Red.tint40, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Red.shade30, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.Pumpkin.tint40, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Pumpkin.shade30, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.Peach.tint40, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Peach.shade30, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.Marigold.tint40, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Marigold.shade30, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.Gold.tint40, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Gold.shade30, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.Brass.tint40, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Brass.shade30, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.Brown.tint40, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Brown.shade30, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.Forest.tint40, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Forest.shade30, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.Seafoam.tint40, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Seafoam.shade30, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.DarkGreen.tint40, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.DarkGreen.shade30, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.LightTeal.tint40, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.LightTeal.shade30, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.Teal.tint40, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Teal.shade30, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.Steel.tint40, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Steel.shade30, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.Blue.tint40, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Blue.shade30, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.RoyalBlue.tint40, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.RoyalBlue.shade30, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.Cornflower.tint40, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Cornflower.shade30, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.Navy.tint40, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Navy.shade30, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.Lavender.tint40, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Lavender.shade30, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.Purple.tint40, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Purple.shade30, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.Grape.tint40, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Grape.shade30, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.Lilac.tint40, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Lilac.shade30, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.Pink.tint40, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Pink.shade30, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.Magenta.tint40, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Magenta.shade30, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.Plum.tint40, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Plum.shade30, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.Beige.tint40, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Beige.shade30, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.Mink.tint40, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Mink.shade30, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.Platinum.tint40, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Platinum.shade30, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.Anchor.tint40, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Anchor.shade30, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil)] 
		}

		//MARK: textCalculatedForegroundColors 
		open var textCalculatedForegroundColors: [UIColor] { 
			return [
			UIColor(light: mainProxy().Colors.DarkRed.shade30, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.DarkRed.tint40, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.Cranberry.shade30, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Cranberry.tint40, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.Red.shade30, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Red.tint40, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.Pumpkin.shade30, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Pumpkin.tint40, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.Peach.shade30, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Peach.tint40, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.Marigold.shade30, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Marigold.tint40, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.Gold.shade30, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Gold.tint40, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.Brass.shade30, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Brass.tint40, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.Brown.shade30, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Brown.tint40, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.Forest.shade30, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Forest.tint40, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.Seafoam.shade30, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Seafoam.tint40, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.DarkGreen.shade30, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.DarkGreen.tint40, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.LightTeal.shade30, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.LightTeal.tint40, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.Teal.shade30, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Teal.tint40, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.Steel.shade30, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Steel.tint40, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.Blue.shade30, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Blue.tint40, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.RoyalBlue.shade30, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.RoyalBlue.tint40, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.Cornflower.shade30, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Cornflower.tint40, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.Navy.shade30, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Navy.tint40, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.Lavender.shade30, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Lavender.tint40, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.Purple.shade30, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Purple.tint40, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.Grape.shade30, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Grape.tint40, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.Lilac.shade30, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Lilac.tint40, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.Pink.shade30, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Pink.tint40, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.Magenta.shade30, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Magenta.tint40, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.Plum.shade30, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Plum.tint40, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.Beige.shade30, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Beige.tint40, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.Mink.shade30, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Mink.tint40, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.Platinum.shade30, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Platinum.tint40, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil), 
			UIColor(light: mainProxy().Colors.Anchor.shade30, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Anchor.tint40, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil)] 
		}

		//MARK: - textFont
		open var textFont: textFontAppearanceProxy {
			return textFontAppearanceProxy(proxy: mainProxy)
		}
		open class textFontAppearanceProxy {
			public let mainProxy: () -> FluentUIStyle
			public init(proxy: @escaping () -> FluentUIStyle) {
				self.mainProxy = proxy
			}

			//MARK: large 
			open var large: UIFont { 
					return UIFont.font(name: nil, size: 15.0, textStyle: nil, weight: UIFont.Weight.regular, traits: [], isScalable: false) 
			}

			//MARK: medium 
			open var medium: UIFont { 
					return UIFont.font(name: nil, size: 13.0, textStyle: nil, weight: UIFont.Weight.regular, traits: [], isScalable: false) 
			}

			//MARK: small 
			open var small: UIFont { 
					return UIFont.font(name: nil, size: 12.0, textStyle: nil, weight: UIFont.Weight.regular, traits: [], isScalable: false) 
			}

			//MARK: xSmall 
			open var xSmall: UIFont { 
					return UIFont.font(name: nil, size: 9.0, textStyle: nil, weight: UIFont.Weight.regular, traits: [], isScalable: false) 
			}

			//MARK: xlarge 
			open var xlarge: UIFont { 
					return UIFont.font(name: nil, size: 20.0, textStyle: nil, weight: UIFont.Weight.regular, traits: [], isScalable: false) 
			}

			//MARK: xxlarge 
			open var xxlarge: UIFont { 
					return UIFont.font(name: nil, size: 28.0, textStyle: nil, weight: UIFont.Weight.medium, traits: [], isScalable: false) 
			}
		}

	}
	//MARK: - MSFGroupAvatarTokens
	open var MSFGroupAvatarTokens: MSFGroupAvatarTokensAppearanceProxy {
		return MSFGroupAvatarTokensAppearanceProxy(proxy: { return self })
	}
	open class MSFGroupAvatarTokensAppearanceProxy: MSFAvatarTokensAppearanceProxy {

		//MARK: - MSFGroupAvatarTokensborderRadius
		open override var borderRadius: MSFGroupAvatarTokensborderRadiusAppearanceProxy {
			return MSFGroupAvatarTokensborderRadiusAppearanceProxy(proxy: mainProxy)
		}
		open class MSFGroupAvatarTokensborderRadiusAppearanceProxy: MSFAvatarTokensAppearanceProxy.borderRadiusAppearanceProxy {

			//MARK: large 
			open override var large: CGFloat { 
					return mainProxy().Border.radius.large 
			}

			//MARK: medium 
			open override var medium: CGFloat { 
					return mainProxy().Border.radius.medium 
			}

			//MARK: small 
			open override var small: CGFloat { 
					return mainProxy().Border.radius.medium 
			}

			//MARK: xSmall 
			open override var xSmall: CGFloat { 
					return mainProxy().Border.radius.small 
			}

			//MARK: xlarge 
			open override var xlarge: CGFloat { 
					return mainProxy().Border.radius.large 
			}

			//MARK: xxlarge 
			open override var xxlarge: CGFloat { 
					return mainProxy().Border.radius.xlarge 
			}
		}

	}
	//MARK: - MSFOutlinedAvatarTokens
	open var MSFOutlinedAvatarTokens: MSFOutlinedAvatarTokensAppearanceProxy {
		return MSFOutlinedAvatarTokensAppearanceProxy(proxy: { return self })
	}
	open class MSFOutlinedAvatarTokensAppearanceProxy: MSFAvatarTokensAppearanceProxy {

		//MARK: backgroundDefaultColor 
		open override var backgroundDefaultColor: UIColor { 
			return UIColor(light: mainProxy().Colors.Neutral.grey94, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Neutral.grey26, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil) 
		}

		//MARK: foregroundDefaultColor 
		open override var foregroundDefaultColor: UIColor { 
			return UIColor(light: mainProxy().Colors.Neutral.grey42, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Neutral.grey78, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil) 
		}

		//MARK: ringDefaultColor 
		open override var ringDefaultColor: UIColor { 
			return mainProxy().Colors.Background.neutralDisabled 
		}
	}
	//MARK: - MSFOutlinedPrimaryAvatarTokens
	open var MSFOutlinedPrimaryAvatarTokens: MSFOutlinedPrimaryAvatarTokensAppearanceProxy {
		return MSFOutlinedPrimaryAvatarTokensAppearanceProxy(proxy: { return self })
	}
	open class MSFOutlinedPrimaryAvatarTokensAppearanceProxy: MSFAvatarTokensAppearanceProxy {

		//MARK: backgroundDefaultColor 
		open override var backgroundDefaultColor: UIColor { 
			return UIColor(light: mainProxy().Colors.Brand.tint40, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Neutral.grey26, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil) 
		}

		//MARK: foregroundDefaultColor 
		open override var foregroundDefaultColor: UIColor { 
			return UIColor(light: mainProxy().Colors.Brand.primary, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Neutral.grey78, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil) 
		}

		//MARK: ringDefaultColor 
		open override var ringDefaultColor: UIColor { 
			return UIColor(light: mainProxy().Colors.Brand.tint10, lightHighContrast: nil, lightElevated: nil, lightElevatedHighContrast: nil, dark: mainProxy().Colors.Neutral.grey78, darkHighContrast: nil, darkElevated: nil, darkElevatedHighContrast: nil) 
		}
	}
	//MARK: - MSFOverflowAvatarTokens
	open var MSFOverflowAvatarTokens: MSFOverflowAvatarTokensAppearanceProxy {
		return MSFOverflowAvatarTokensAppearanceProxy(proxy: { return self })
	}
	open class MSFOverflowAvatarTokensAppearanceProxy: MSFAvatarTokensAppearanceProxy {

		//MARK: backgroundDefaultColor 
		open override var backgroundDefaultColor: UIColor { 
			return mainProxy().Colors.Background.neutral4 
		}

		//MARK: foregroundDefaultColor 
		open override var foregroundDefaultColor: UIColor { 
			return mainProxy().Colors.Foreground.neutral3 
		}

		//MARK: ringDefaultColor 
		open override var ringDefaultColor: UIColor { 
			return mainProxy().Colors.Background.neutralDisabled 
		}
	}

}
fileprivate var __AppearanceProxyHandle: UInt8 = 0
fileprivate var __ThemeAwareHandle: UInt8 = 0
fileprivate var __ObservingDidChangeThemeHandle: UInt8 = 0

extension MSFAvatarTokens: AppearaceProxyComponent {

	public typealias AppearanceProxyType = FluentUIStyle.MSFAvatarTokensAppearanceProxy
	public var appearanceProxy: AppearanceProxyType {
		get {
			if let proxy = objc_getAssociatedObject(self, &__AppearanceProxyHandle) as? AppearanceProxyType {
				if !themeAware { return proxy }

				if let proxyString = Optional(String(reflecting: type(of: proxy))), proxyString.hasPrefix("FluentUI") == false {
					return proxy
				}

				if proxy is FluentUIStyle.MSFAccentAvatarTokensAppearanceProxy {
					return FluentUIThemeManager.stylesheet(FluentUIStyle.shared()).MSFAccentAvatarTokens
				} else if proxy is FluentUIStyle.MSFGroupAvatarTokensAppearanceProxy {
					return FluentUIThemeManager.stylesheet(FluentUIStyle.shared()).MSFGroupAvatarTokens
				} else if proxy is FluentUIStyle.MSFOutlinedAvatarTokensAppearanceProxy {
					return FluentUIThemeManager.stylesheet(FluentUIStyle.shared()).MSFOutlinedAvatarTokens
				} else if proxy is FluentUIStyle.MSFOutlinedPrimaryAvatarTokensAppearanceProxy {
					return FluentUIThemeManager.stylesheet(FluentUIStyle.shared()).MSFOutlinedPrimaryAvatarTokens
				} else if proxy is FluentUIStyle.MSFOverflowAvatarTokensAppearanceProxy {
					return FluentUIThemeManager.stylesheet(FluentUIStyle.shared()).MSFOverflowAvatarTokens
				}
				return proxy
			}

			return FluentUIThemeManager.stylesheet(FluentUIStyle.shared()).MSFAvatarTokens
		}
		set {
			objc_setAssociatedObject(self, &__AppearanceProxyHandle, newValue, .OBJC_ASSOCIATION_RETAIN_NONATOMIC)
			didChangeAppearanceProxy()
		}
	}

	public var themeAware: Bool {
		get {
			guard let proxy = objc_getAssociatedObject(self, &__ThemeAwareHandle) as? Bool else { return true }
			return proxy
		}
		set {
			objc_setAssociatedObject(self, &__ThemeAwareHandle, newValue, .OBJC_ASSOCIATION_RETAIN_NONATOMIC)
			isObservingDidChangeTheme = newValue
		}
	}

	fileprivate var isObservingDidChangeTheme: Bool {
		get {
			guard let observing = objc_getAssociatedObject(self, &__ObservingDidChangeThemeHandle) as? Bool else { return false }
			return observing
		}
		set {
			if newValue == isObservingDidChangeTheme { return }
			if newValue {
				NotificationCenter.default.addObserver(self, selector: #selector(didChangeAppearanceProxy), name: Notification.Name.didChangeTheme, object: nil)
			} else {
				NotificationCenter.default.removeObserver(self, name: Notification.Name.didChangeTheme, object: nil)
			}
			objc_setAssociatedObject(self, &__ObservingDidChangeThemeHandle, newValue, .OBJC_ASSOCIATION_RETAIN_NONATOMIC)
		}
	}
}
