jobs:
- job: credScan
  displayName: Secure Development Tools
  variables:
    tags: production, externalfacing
  pool:
    vmImage: windows-2019
  steps:
  - template: vss-secure-development-tools.yml

- job: fluentui_apple_publish_nuget
  pool:
    vmImage: 'macos-11'
  variables:
  - name: BUILDSECMON_OPT_IN
    value: true
  displayName: FluentUI Apple Publish NuGet
  timeoutInMinutes: 60 # how long to run the job before automatically cancelling
  cancelTimeoutInMinutes: 5 # how much time to give 'run always even if cancelled tasks' before killing them
  
  steps:
  # Select proper Xcode version
  - template: apple-xcode-select.yml

  # Build and zip the libraries
  - template: fluentui-apple-build-zip.yml

  # generate the sanitizedBuildNumber environment variable
  - bash: 'scripts/generate_build_number.sh'
    displayName: 'Generate Build Number'

  # pack the nuspec
  - task: NuGetCommand@2
    displayName: 'NuGet pack'
    inputs:
      command: pack
      packagesToPack: 'FluentUI.nuspec'
      buildProperties: buildNumber=$(sanitizedBuildNumber);commitId=$(Build.SourceVersion);repoUri=$(Build.Repository.Uri)

  - task: AzureArtifacts.manifest-generator-task.manifest-generator-task.ManifestGeneratorTask@0
    displayName: 'Generation Task'
    inputs:
      BuildDropPath: '$(System.DefaultWorkingDirectory)'

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Manifest'
    inputs:
      artifactName: SBom-$(System.JobAttempt)
      targetPath: '$(System.DefaultWorkingDirectory)/_manifest'

  # push the package package
  - task: NuGetCommand@2
    displayName: 'NuGet push'
    inputs:
      command: push
      packagesToPush: '$(Build.ArtifactStagingDirectory)/Microsoft.FluentUI.Apple.*.nupkg'
      publishVstsFeed: Office
