jobs:
- job: fluentui_apple_publish_nuget
  pool:
    vmImage: 'macos-10.15'
  displayName: FluentUI Apple Publish NuGet
  timeoutInMinutes: 60 # how long to run the job before automatically cancelling
  cancelTimeoutInMinutes: 5 # how much time to give 'run always even if cancelled tasks' before killing them
  
  steps:
  # - task: Npm@1
  #   displayName: 'npm install'
  #   inputs:
  #     verbose: false

  # macOS Framework Debug
  - template: apple-xcode-build.yml
    parameters:
      xcode_sdk: 'macosx'
      xcode_workspacePath: 'macos/xcode/FluentUI.xcodeproj'
      xcode_actions: 'build'
      xcode_scheme: 'FluentUI-macOS'
      xcode_configuration: 'Debug'
      xcode_extraArgs: '-xcconfig $(Build.Repository.LocalPath)/.ado/xcconfig/publish_overrides.xcconfig'
  
  # macOS Framework Release
  - template: apple-xcode-build.yml
    parameters:
      xcode_sdk: 'macosx'
      xcode_workspacePath: 'macos/xcode/FluentUI.xcodeproj'
      xcode_actions: 'build'
      xcode_scheme: 'FluentUI-macOS'
      xcode_configuration: 'Release'
      xcode_extraArgs: '-xcconfig $(Build.Repository.LocalPath)/.ado/xcconfig/publish_overrides.xcconfig'

  # iphonesimulator Library Debug
  - template: apple-xcode-build.yml
    parameters:
      xcode_sdk: 'iphonesimulator'
      xcode_workspacePath: 'ios/FluentUI.xcworkspace'
      xcode_actions: 'build test'
      xcode_scheme: 'FluentUI-iOS'
      xcode_configuration: 'Debug'
      xcode_extraArgs: '-xcconfig $(Build.Repository.LocalPath)/.ado/xcconfig/publish_overrides.xcconfig'
  
  # iphonesimulator Library Release
  - template: apple-xcode-build.yml
    parameters:
      xcode_sdk: 'iphonesimulator'
      xcode_workspacePath: 'ios/FluentUI.xcworkspace'
      xcode_actions: 'build'
      xcode_scheme: 'FluentUI-iOS'
      xcode_configuration: 'Release'
      xcode_extraArgs: '-xcconfig $(Build.Repository.LocalPath)/.ado/xcconfig/publish_overrides.xcconfig'

  # iphoneos Library Debug
  - template: apple-xcode-build.yml
    parameters:
      xcode_sdk: 'iphoneos'
      xcode_workspacePath: 'ios/FluentUI.xcworkspace'
      xcode_actions: 'build test'
      xcode_scheme: 'FluentUI-iOS'
      xcode_configuration: 'Debug'
      xcode_extraArgs: '-xcconfig $(Build.Repository.LocalPath)/.ado/xcconfig/publish_overrides.xcconfig'
  
  # iphoneos Library Release
  - template: apple-xcode-build.yml
    parameters:
      xcode_sdk: 'iphoneos'
      xcode_workspacePath: 'ios/FluentUI.xcworkspace'
      xcode_actions: 'build'
      xcode_scheme: 'FluentUI-iOS'
      xcode_configuration: 'Release'
      xcode_extraArgs: '-xcconfig $(Build.Repository.LocalPath)/.ado/xcconfig/publish_overrides.xcconfig'
      
  # - bash: 'scripts/prepare_for_nuget_pack.sh'
  #   displayName: 'Zip frameworks to preserve symlinks'

  # generate the nuspecsToPack and sanitizedBuildNumber environment variables

  # - script: 'node scripts/vsto-collect-nuspec.js apple'
  #   displayName: 'Generate versioned nuspec files'

  # pack all the nuspecs

  # - task: NuGetCommand@2
  #   displayName: 'NuGet pack'
  #   inputs:
  #     command: pack
  #     packagesToPack: '$(nuspecsToPack)'
  #     buildProperties: buildNumber=$(sanitizedBuildNumber);commitId=$(Build.SourceVersion);repoUri=$(Build.Repository.Uri)

  # push packages

  # - task: PublishBuildArtifacts@1
  #   displayName: 'Publish Artifact: OfficeUIFabricmacOSNuPkg'
  #   inputs:
  #     ArtifactName: OfficeUIFabricmacOSNuPkg
  #   condition: succeededOrFailed()
