platform :osx, '10.11'
use_frameworks!
inhibit_all_warnings!

target 'sgen' do
  pod 'Commander', '~> 0.8'
  pod 'PathKit', '~> 1.0.0'
  pod 'xcodeproj', '~> 7.14.0'
  pod 'Yaml', '~> 3.4.4'

end

#pre_install do |installer|
#  installer.analysis_result.specifications.each do |s|
#    s.swift_version = '4.2' unless s.swift_version
#  end
#end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
    end
  end
end
