// swiftlint:disable all
/// Autogenerated file
import UIKit

/// Entry point for the app stylesheet
extension FluentUIStyle {

	// MARK: - MSFHeaderFooterTokens
	open var MSFHeaderFooterTokens: MSFHeaderFooterTokensAppearanceProxy {
		return MSFHeaderFooterTokensAppearanceProxy(proxy: { return self })
	}
	open class MSFHeaderFooterTokensAppearanceProxy {
		public let mainProxy: () -> FluentUIStyle
		public init(proxy: @escaping () -> FluentUIStyle) {
			self.mainProxy = proxy
		}

		// MARK: - backgroundColor 
		open var backgroundColor: UIColor {
			return mainProxy().Colors.Background.neutral1
		}

		// MARK: - bottomPadding 
		open var bottomPadding: CGFloat {
			return mainProxy().Spacing.xSmall
		}

		// MARK: - headerHeight 
		open var headerHeight: CGFloat {
			return mainProxy().Spacing.xxxLarge
		}

		// MARK: - leadingPadding 
		open var leadingPadding: CGFloat {
			return mainProxy().Spacing.medium
		}

		// MARK: - textColor 
		open var textColor: UIColor {
			return mainProxy().Colors.Foreground.neutral3
		}

		// MARK: - textFont 
		open var textFont: UIFont {
			return mainProxy().Typography.caption1
		}

		// MARK: - topPadding 
		open var topPadding: CGFloat {
			return mainProxy().Spacing.xLarge
		}

		// MARK: - trailingPadding 
		open var trailingPadding: CGFloat {
			return mainProxy().Spacing.medium
		}
	}
	// MARK: - MSFPrimaryHeaderTokens
	open var MSFPrimaryHeaderTokens: MSFPrimaryHeaderTokensAppearanceProxy {
		return MSFPrimaryHeaderTokensAppearanceProxy(proxy: { return self })
	}
	open class MSFPrimaryHeaderTokensAppearanceProxy: MSFHeaderFooterTokensAppearanceProxy {

		// MARK: - textColor 
		open override var textColor: UIColor {
			return mainProxy().Colors.Foreground.neutral1
		}

		// MARK: - textFont 
		open override var textFont: UIFont {
			return mainProxy().Typography.headline
		}

		// MARK: - topPadding 
		open override var topPadding: CGFloat {
			return mainProxy().Spacing.medium
		}
	}

}
fileprivate var __AppearanceProxyHandle: UInt8 = 0
fileprivate var __ThemeAwareHandle: UInt8 = 0
fileprivate var __ObservingDidChangeThemeHandle: UInt8 = 0

extension MSFHeaderFooterTokens: AppearaceProxyComponent {

	public typealias AppearanceProxyType = FluentUIStyle.MSFHeaderFooterTokensAppearanceProxy
	public var appearanceProxy: AppearanceProxyType {
		get {
			if let proxy = objc_getAssociatedObject(self, &__AppearanceProxyHandle) as? AppearanceProxyType {
				if !themeAware { return proxy }

				if let proxyString = Optional(String(reflecting: type(of: proxy))), proxyString.hasPrefix("FluentUI") == false {
					return proxy
				}

				if proxy is FluentUIStyle.MSFPrimaryHeaderTokensAppearanceProxy {
					return FluentUIThemeManager.stylesheet(FluentUIStyle.shared()).MSFPrimaryHeaderTokens
				}
				return proxy
			}

			return FluentUIThemeManager.stylesheet(FluentUIStyle.shared()).MSFHeaderFooterTokens
		}
		set {
			objc_setAssociatedObject(self, &__AppearanceProxyHandle, newValue, .OBJC_ASSOCIATION_RETAIN_NONATOMIC)
			didChangeAppearanceProxy()
		}
	}

	public var themeAware: Bool {
		get {
			guard let proxy = objc_getAssociatedObject(self, &__ThemeAwareHandle) as? Bool else { return true }
			return proxy
		}
		set {
			objc_setAssociatedObject(self, &__ThemeAwareHandle, newValue, .OBJC_ASSOCIATION_RETAIN_NONATOMIC)
			isObservingDidChangeTheme = newValue
		}
	}

	fileprivate var isObservingDidChangeTheme: Bool {
		get {
			guard let observing = objc_getAssociatedObject(self, &__ObservingDidChangeThemeHandle) as? Bool else { return false }
			return observing
		}
		set {
			if newValue == isObservingDidChangeTheme { return }
			if newValue {
				NotificationCenter.default.addObserver(self, selector: #selector(didChangeAppearanceProxy), name: Notification.Name.didChangeTheme, object: nil)
			} else {
				NotificationCenter.default.removeObserver(self, name: Notification.Name.didChangeTheme, object: nil)
			}
			objc_setAssociatedObject(self, &__ObservingDidChangeThemeHandle, newValue, .OBJC_ASSOCIATION_RETAIN_NONATOMIC)
		}
	}
}
